version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017


  project-socialnetwork-app:
    image: laersonjr/project-socialnetwork-app:latest
    build: .
    container_name: project-socialnetwork-app
    ports:
      - 8082:8082